server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Suruchi1809/config-repo # Replace with your GitHub repository
          search-paths: config
