server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:admindb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

      spring:
  zipkin:
    base-url: http://localhost:9411  # The URL where your Zipkin server is running
    enabled: true                     # Enables Zipkin tracing
  sleuth:
    sampler:
      probability: 1.0                # Adjusts the sampling rate for tracing (1.0 means 100% of requests will be traced)

