server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/users/**
        - id: flight-management
          uri: lb://FLIGHT-MANAGEMENT-SERVICE
          predicates:
            - Path=/flights/**
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**
        - id: admin-management
          uri: lb://ADMIN-MANAGEMENT-SERVICE
          predicates:
            - Path=/admins/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

      spring:
  zipkin:
    base-url: http://localhost:9411  # Points to your running Zipkin server (Docker in this case)
    enabled: true                    # Enables Zipkin tracing
  sleuth:
    sampler:
      probability: 1.0               # Ensures 100% of requests are traced

