server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:flightdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

      spring:
  zipkin:
    base-url: http://localhost:9411  # Points to your running Zipkin server (Docker in this case)
    enabled: true                    # Enables Zipkin tracing
  sleuth:
    sampler:
      probability: 1.0               # Ensures 100% of requests are traced

